# @Author: Ya Han
# @Dat: 2021-04-14
# @Last Modified by: Ya
# @Last Modified time: 2021-07-04

# Note:
# Pseudo-bulk ATAC-seq profiles are generated by pooling together cells within each cell type.
# For the formed pseudo-bulk samples,to identify potentially rare cis-elements that were missed from the aggregated peak calls in the earlier step of the scATAC-seq analysis, we called peaks on each cell cluster separately.


# Acivate conda environment
source activate /fs/home/hanya/miniconda3/envs/MAESTRO


# run the following command for detailed usage of tools.
sinto filterbarcodes --help
samtools merge       --help

# the following commands can be used for format conversion
sinto filterbarcodes          # Subset reads from a BAM file by cell barcode
samtools merge           # Merge bam file


# Examples:
sinto filterbarcodes -b /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P12_Tumor/Result/minimap2/P12_Tumor.sortedByPos.rmdp.CBadded.bam \
-c /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Integrate_RNAseq_scATAC/Seerated_celltype/TNK_subcelltype_transfor/Subset_cd8/Cell_type_infor/P12_TumorCell_according_barcode.txt \
-p 8

samtools merge /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/CD8_GZMK_merge.bam \
/mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P05_OLK/Result/CD8_GZMK.bam /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P05_Tumor/Result/CD8_GZMK.bam /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P10_OLK/Result/CD8_GZMK.bam /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P10_Tumor/Result/CD8_GZMK.bam /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P11_Tumor/Result/CD8_GZMK.bam /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P12_OLP/Result/CD8_GZMK.bam /mnt/Storage2/home/hanya/project/Carcinogenesis/scATAC/Maestro_process_ATAC/Maestro_seperate_process_sample/P12_Tumor/Result/CD8_GZMK.bam  --threads 2




