#' Identify the association between mutation state and module gene score
#' @param Module_score Module score of each mini-cluster
#' @param Mutation_sig The mutation information rds file, two coulmns and first is sample and second is gene symbol
#' @param Mini_cluster_info The RData file of mini-cluster information generated by scRNA_WGCNA.R
#' @param output_dir Path of output file
#' @author Ya Han

library(WGCNA)
library(Seurat)
library(tidyverse)
library(reshape2)
library(stringr)


Batch_mutation_module_gene_score<-function(Module_score,Mutation_sig,Mini_cluster_info,output_dir=NULL){
  load(Mini_cluster_info)
  result=unlist(lapply(Cell_minicluster_list,function(x) return(length(x))))
  #然后对于那种只有一个cell 的，我们删掉那种只包含了少于5个cell的mini-cluster.
  less_than_5_index=which(result < 5)
  Sample=as.vector(unlist(lapply(strsplit(colname_source_cluster[-1*less_than_5_index],"\\|"),function(x) x[1])))
  Mutation_sig=readRDS(Mutation_sig)
  if(length(Module_score)=1){
    MEs=readRDS(Module_score)
  }
  MEs=Module_score
 
  
  Module_mutaion<<-NULL
  batch_mutation_effect_on_Module_score<-function(mut_gene){
    mut_samp=unique(Mutation_sig[which(Mutation_sig[,2] == mut_gene),1])
    Mutation_meta=rep("Wild_type",length(Sample))
    Mutation_meta[which(Sample %in% mut_samp)]="Mutation"
    if(length(table(Mutation_meta)) > 1){
      wilcox_each_module<-function(temp_model){
        data=data.frame(Module_score=MEs[,temp_model],Mutation=Mutation_meta)
        #aggregate(Module_score~Mutation,data,mean)
        temp_result=c(temp_model,mut_gene,unlist(wilcox.test(Module_score~Mutation,data))[2])
        Module_mutaion<<-rbind(Module_mutaion,temp_result)
      }
      result=apply(matrix(colnames(MEs)),1,wilcox_each_module)
  
    }
  }
  result=apply(matrix(unique(Mutation_sig[,2])),1,batch_mutation_effect_on_Module_score)
  
 

  Mutation_effect=as.data.frame(Module_mutaion)
  colnames(Mutation_effect)=c("Module_name","Gene","P_value")
  Mutation_effect$P_value=as.numeric(as.vector(Mutation_effect$P_value))
  Mutation_effect$P_adjust=p.adjust(Mutation_effect$P_value)
  

  Gene_Mut_fre=table(Mutation_sig[,2])
  Mutation_effect$Mutation_Fre=Gene_Mut_fre[match(Mutation_effect$Gene,names(Gene_Mut_fre))]
  
  write.table(Mutation_effect,file="Module_mutaion_gene_Wild_Mut_Padjust.txt",col.names = T,row.names = F,sep="\t",quote = F)
  saveRDS(Mutation_effect,"Module_mutaion_gene_Wild_Mut_Padjust.rds")
}

